### ISSUE TITLE
Change name of repository?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/RSPARROW#1]

**Comment by ldecicco-USGS** [comment]
What's wrong with the name? Sparrow traditionally is spelled out in journals and whatnot as SPARROW...

**Comment by jread-usgs** [comment]
`SPARROW` or `PARROT`?

**Comment by ldecicco-USGS** [comment]
What are you talking about?

**Comment by jread-usgs** [comment]
as recommended names: SPARROW or PARROT. Maybe I don't understand the scope of the package, but if this is to be the canonical SPARROW model in the future, prefixing it w/ `r` makes it seem like the real model exists elsewhere and this is an R port of that. I thought this was a re-boot that would replace SPARROW in the future, hence the suggestion to name this package as if you were thinking about the preferred name 3~5 years down the road.

**Comment by gudaleon** [comment]
sorry to intervene, as a SPARROW user please keep the original name to maintain recognition by the general audience. There are way too many models which totally confuses the stakeholders. There is pySPARROW version already, nothing wrong with rSPARROW. You can add v2 or BayesSPARROW if it will include Bayesian Inference.
